# FROM eclipse-temurin:8u432-b06-jre-ubi9-minimal

# RUN apt update
# RUN apt 
# RUN apt -y install gradle
# RUN wget https://assets.hikvision.com/prd/public/all/files/202404/1712107834101/SADP240312.zip

FROM gradle:jdk23-corretto

