version: '3'
services:
  fastapi:
    image: darlon/fastapi:1.0
#    build: .
    ports:
      - 8000:8000
    volumes:
      - ./project:/data
#    tty: true
#        restart: always
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload

