version: '3'
services:
  server:
    image: darlon/fastapi_linux:1.0
    build: ./server/
    ports:
      - 8000:8000
    volumes:
      - ./project:/data
#    tty: true
#        restart: always
    command: uvicorn main:app --host=0.0.0.0 --port=8000 --reload
  client:
    build: ./client/
    volumes:
      - ./project:/data
    tty: true

